const fs = require('node:fs')
const path = require('node:path')
const { withAppBuildGradle, withDangerousMod } = require('expo/config-plugins')

const MARKER = '// AgentsDock Android distribution channels (generated by withAndroidSideloadUpdater)'
const FLAVORS = `${MARKER}
    flavorDimensions += "distribution"
    productFlavors {
        sideload {
            dimension "distribution"
            buildConfigField "boolean", "AGENTSDOCK_SIDELOAD_UPDATER", "true"
        }
        play {
            dimension "distribution"
            buildConfigField "boolean", "AGENTSDOCK_SIDELOAD_UPDATER", "false"
        }
    }
`
const SIDELOAD_MANIFEST = `<manifest xmlns:android="http://schemas.android.com/apk/res/android">
  <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
</manifest>
`

function applyAndroidSideloadUpdater(contents) {
  if (contents.includes(MARKER)) return contents
  const packagingOptions = '    packagingOptions {'
  if (!contents.includes(packagingOptions)) {
    throw new Error('Unable to find Expo\'s generated Android packagingOptions block')
  }
  return contents.replace(packagingOptions, `${FLAVORS}\n${packagingOptions}`)
}

module.exports = function withAndroidSideloadUpdater(config) {
  config = withAppBuildGradle(config, next => {
    if (next.modResults.language !== 'groovy') {
      throw new Error('AgentsDock Android updater requires a Groovy app build.gradle')
    }
    next.modResults.contents = applyAndroidSideloadUpdater(next.modResults.contents)
    return next
  })
  return withDangerousMod(config, ['android', async next => {
    const manifestPath = path.join(next.modRequest.platformProjectRoot, 'app', 'src', 'sideload', 'AndroidManifest.xml')
    fs.mkdirSync(path.dirname(manifestPath), { recursive: true })
    fs.writeFileSync(manifestPath, SIDELOAD_MANIFEST)
    return next
  }])
}

module.exports.applyAndroidSideloadUpdater = applyAndroidSideloadUpdater
module.exports.MARKER = MARKER
module.exports.SIDELOAD_MANIFEST = SIDELOAD_MANIFEST
