const { withAppBuildGradle } = require('expo/config-plugins')

const MARKER = '// AgentsDock production Android signing (generated by withAndroidReleaseSigning)'
const DEBUG_SIGNING_BLOCK = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`
const RELEASE_DEBUG_SIGNING = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`

const ENVIRONMENT_SETUP = `${MARKER}
def agentsDockReleaseSigning = [
    storeFile: System.getenv('AGENTSDOCK_ANDROID_KEYSTORE_PATH'),
    storePassword: System.getenv('AGENTSDOCK_ANDROID_KEYSTORE_PASSWORD'),
    keyAlias: System.getenv('AGENTSDOCK_ANDROID_KEY_ALIAS'),
    keyPassword: System.getenv('AGENTSDOCK_ANDROID_KEY_PASSWORD'),
]
def agentsDockReleaseSigningConfigured = agentsDockReleaseSigning.values().every { value ->
    value != null && !value.trim().isEmpty()
}

gradle.taskGraph.whenReady { graph ->
    def releaseTaskRequested = graph.allTasks.any { task ->
        task.name.toLowerCase().contains('release')
    }
    if (releaseTaskRequested && !agentsDockReleaseSigningConfigured) {
        throw new GradleException(
            'Android release signing is required. Set the four AGENTSDOCK_ANDROID_* signing variables.'
        )
    }
}
`

const RELEASE_SIGNING_BLOCK = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            storeFile agentsDockReleaseSigningConfigured ? file(agentsDockReleaseSigning.storeFile) : file('debug.keystore')
            storePassword agentsDockReleaseSigningConfigured ? agentsDockReleaseSigning.storePassword : 'android'
            keyAlias agentsDockReleaseSigningConfigured ? agentsDockReleaseSigning.keyAlias : 'androiddebugkey'
            keyPassword agentsDockReleaseSigningConfigured ? agentsDockReleaseSigning.keyPassword : 'android'
        }
    }`

function applyAndroidReleaseSigning(contents) {
  if (contents.includes(MARKER)) return contents
  if (!contents.includes('android {')) {
    throw new Error('Unable to find the Android application block for release signing')
  }
  if (!contents.includes(DEBUG_SIGNING_BLOCK)) {
    throw new Error('Unable to find Expo\'s generated debug signing block')
  }
  if (!contents.includes(RELEASE_DEBUG_SIGNING)) {
    throw new Error('Unable to find Expo\'s generated release signing assignment')
  }

  return contents
    .replace('android {', `${ENVIRONMENT_SETUP}\nandroid {`)
    .replace(DEBUG_SIGNING_BLOCK, RELEASE_SIGNING_BLOCK)
    .replace(RELEASE_DEBUG_SIGNING, `        release {\n            signingConfig signingConfigs.release`)
}

module.exports = function withAndroidReleaseSigning(config) {
  return withAppBuildGradle(config, next => {
    if (next.modResults.language !== 'groovy') {
      throw new Error('AgentsDock Android release signing requires a Groovy app build.gradle')
    }
    next.modResults.contents = applyAndroidReleaseSigning(next.modResults.contents)
    return next
  })
}

module.exports.applyAndroidReleaseSigning = applyAndroidReleaseSigning
module.exports.MARKER = MARKER
