import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const dialogs = fs.readFileSync(path.resolve('src/components/Dialogs.tsx'), 'utf8')
const defaultAnalyticsSettings = fs.readFileSync(path.resolve('src/components/AnalyticsSettings.tsx'), 'utf8')
const androidAnalyticsSettings = fs.readFileSync(path.resolve('src/components/AnalyticsSettings.android.tsx'), 'utf8')
const app = fs.readFileSync(path.resolve('App.tsx'), 'utf8')
const defaultAnalytics = fs.readFileSync(path.resolve('src/lib/analytics.ts'), 'utf8')
const analytics = fs.readFileSync(path.resolve('src/lib/analytics.android.ts'), 'utf8')
const iosAnalytics = fs.readFileSync(path.resolve('src/lib/analytics.ios.ts'), 'utf8')
const analyticsPayload = fs.readFileSync(path.resolve('src/lib/analytics-payload.ts'), 'utf8')
const policy = fs.readFileSync(path.resolve('../website/privacy.html'), 'utf8')

test('iOS opens without analytics UI while Android retains its opt-out control', () => {
  assert.match(app, /<AppShell \/>/)
  assert.doesNotMatch(app, /AnalyticsConsentDialog|analyticsConsentResolved/)
  assert.doesNotMatch(dialogs, /AnalyticsConsentDialog|analytics-consent-(?:accept|decline)/)
  assert.match(dialogs, /<AnalyticsSettings visible=\{visible\} \/>/)
  assert.match(dialogs, /openPrivacyPolicy[\s\S]*?Linking\.openURL\(PRIVACY_POLICY_URL\)/)
  assert.match(dialogs, /testID="settings-privacy-policy"[\s\S]*?onPress=\{openPrivacyPolicy\}/)
  assert.doesNotMatch(dialogs, /Usage analytics|Mixpanel|settings-analytics-toggle|Share usage analytics/)
  assert.doesNotMatch(dialogs, /settings-copy-analytics-id/)
  assert.match(defaultAnalyticsSettings, /return null/)
  assert.doesNotMatch(defaultAnalyticsSettings, /Usage analytics|Mixpanel|settings-analytics-toggle|Share usage analytics/)
  assert.match(androidAnalyticsSettings, /testID="settings-analytics-toggle"/)
  assert.match(androidAnalyticsSettings, /accessibilityLabel="Share usage analytics"/)
  assert.match(androidAnalyticsSettings, /Sends ID-less usage events to Mixpanel/)
})

test('Android analytics is ID-less, default-on unless explicitly denied, and safely revocable', () => {
  assert.match(analytics, /SecureStore\.deleteItemAsync\(LEGACY_DISTINCT_ID_KEY\)/)
  assert.match(analytics, /value !== 'denied'/)
  assert.match(analytics, /invokedRevision !== preferenceRevision/)
  assert.match(analytics, /MIXPANEL_TRACK_URL/)
  assert.match(analyticsPayload, /distinct_id: ''/)
  assert.match(analytics, /preferencePersistenceQueue/)
  assert.match(analytics, /androidAnalyticsEnabled = enabled[\s\S]*?if \(!enabled\)[\s\S]*?controller\.abort\(\)[\s\S]*?const cleanup = clearLegacyDistinctId\(\)/)
  assert.match(analytics, /for \(const controller of inFlightRequests\) controller\.abort\(\)/)
  assert.match(analytics, /setTimeout\(\(\) => controller\.abort\(\), TRACK_TIMEOUT_MS\)/)
  assert.match(analytics, /signal: controller\.signal/)
  assert.doesNotMatch(analytics, /generateDistinctId|getOrCreateDistinctId|getAnalyticsDistinctId/)
})

test('the iOS-resolved analytics module only removes the obsolete local identifier', () => {
  assert.doesNotMatch(defaultAnalytics, /MIXPANEL|fetch\(|analytics-payload|AsyncStorage|SecureStore/)
  assert.match(iosAnalytics, /SecureStore\.deleteItemAsync\(LEGACY_DISTINCT_ID_KEY\)/)
  assert.match(iosAnalytics, /export function trackEvent/)
  assert.doesNotMatch(iosAnalytics, /MIXPANEL|fetch\(|analytics-payload|AsyncStorage/)
})

test('privacy policy explains platform-specific identifier-free analytics, opt-out, and retention', () => {
  assert.match(policy, /macOS, Windows, Linux, and Android apps, limited usage analytics are <strong>on by default<\/strong>, without a first-run analytics prompt/)
  assert.match(policy, /turn them off at any time in Settings/)
  assert.match(policy, /iOS and iPadOS apps do not send Mixpanel events or other custom usage analytics and do not create or store an app analytics identifier/)
  assert.match(policy, /empty <code>distinct_id<\/code>/)
  assert.match(policy, /On Android, events are sent with an empty <code>distinct_id<\/code> and no persistent identifier/)
  assert.match(policy, /IP-based geolocation disabled \(<code>ip=0<\/code>\)/)
  assert.match(policy, /The Android app sends the same events with no such identifier/)
  assert.match(policy, /do <strong>not<\/strong> include chat content, prompts, agent responses, source code, file names or contents, working-directory paths, server names or addresses, access tokens, terminal output, scheduled-job content, screen recordings, automatic UI capture, or IP-derived location/)
  assert.match(policy, /Mixpanel remains a third-party processor and may handle network request metadata under its own privacy policy/)
  assert.match(policy, /does not automatically delete event records Mixpanel already received/)
  assert.match(policy, /On Android, previously received events carry no such identifier and generally cannot be associated with one installation/)
  assert.match(policy, /retained only while needed to measure feature-adoption and platform-reliability trends/)
  assert.match(policy, /periodically review that need/)
  assert.match(policy, /Google Analytics is scoped to the website and does not run inside the AgentsDock apps/)
  assert.match(policy, /Google may process request information and identifiers under its own privacy policy/)
  assert.match(policy, /Uninstall behavior varies by platform/)
  assert.match(policy, /Uninstalling alone may not clear desktop app data or operating-system secure storage/)
  assert.match(policy, /contact@agentsdock\.net/)
  assert.doesNotMatch(policy, /random app-install analytics ID/)
  assert.doesNotMatch(policy, /pseudonymous/)
  assert.doesNotMatch(policy, /If you opt in/)
  assert.doesNotMatch(policy, /analytics ID shown in Settings/)
})
