import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'
import assert from 'node:assert/strict'

const projection = fs.readFileSync(path.resolve('src/lib/timeline.ts'), 'utf8')
const rows = fs.readFileSync(path.resolve('src/components/TimelineRows.tsx'), 'utf8')
const cards = fs.readFileSync(path.resolve('src/components/CrossChatTimelineCards.tsx'), 'utf8')
const markdown = fs.readFileSync(path.resolve('src/components/MarkdownContent.tsx'), 'utf8')
const inlineReferences = fs.readFileSync(path.resolve('src/lib/timeline-inline-references.ts'), 'utf8')
const types = fs.readFileSync(path.resolve('src/types.ts'), 'utf8')
const memory = fs.readFileSync(path.resolve('src/lib/timeline-memory.ts'), 'utf8')
const rowReuse = fs.readFileSync(path.resolve('src/lib/timeline-row-reuse.ts'), 'utf8')

test('cross-chat lifecycle projection is semantic and internal delivery cannot impersonate a user', () => {
  assert.match(projection, /export function crossChatSemanticKey/)
  assert.match(projection, /cross-chat-exchange:\$\{exchangeId\}/)
  assert.match(projection, /cross-chat:handoff:\$\{handoffId\}/)
  assert.match(projection, /cross-chat:watch:\$\{watchId\}/)
  assert.match(projection, /crossChatTerminalStatusByExchange/)
  assert.match(projection, /crossChatRowsByExchange\.get\(exchangeId\)/)
  assert.match(projection, /event\.purpose === 'cross_chat_handoff_delivery'/)
  assert.match(projection, /const hasVisibleUserContent = Boolean\(messageText\(event\)\.trim\(\) \|\| event\.file_ids\?\.length\)/)
  assert.match(projection, /if \(!isInternalDeliveryTurn\(event\) && hasVisibleUserContent\) active\.user = event/)
  assert.match(projection, /event\.type === 'cross_chat_exchange_failed'/)
  assert.doesNotMatch(projection, /event\.type\.endsWith\('_failed'\)/)
  assert.match(projection, /terminalNormalizedCrossChatEvents/)
  assert.match(projection, /crossChatEventWithStatus\(event, terminalStatus\)/)
  assert.match(projection, /events: \[effectiveEvent\]/)
  assert.match(rows, /events=\{row\.events\}/)
  assert.match(rowReuse, /&& left\.event === right\.event/)
  assert.doesNotMatch(rowReuse, /left\.key\.startsWith\('cross-chat'\).*sameSerializableRecord/s)
})

test('cross-chat cards lazy-load and cancel through scope-fenced server calls', () => {
  assert.match(rows, /<CrossChatHandoffCard/)
  assert.match(rows, /<CrossChatExchangeCard/)
  assert.match(cards, /scope\.connection\.crossChatHandoff\(envelopeId\)/)
  assert.match(cards, /scope\.connection\.cancelCrossChatHandoff\(envelopeId\)/)
  assert.match(cards, /scope\.connection\.crossChatExchange\(exchangeId\)/)
  assert.match(cards, /scope\.connection\.cancelCrossChatExchange\(exchangeId\)/)
  assert.match(cards, /scope\.connection\.skipQueuedCrossChatDelivery\(sessionId, queuedId/)
  assert.match(cards, /client === scope\.connection/)
  assert.match(cards, /scope\.connection\.validationRevision === scope\.validationRevision/)
  assert.match(cards, /state\.activeProfileId === scope\.profileId/)
  assert.match(cards, /state\.profileGeneration === scope\.profileGeneration/)
  assert.match(cards, /state\.selectedSessionId === scope\.sessionId/)
  assert.match(cards, /key=\{`\$\{profileGeneration\}:\$\{props\.sessionId\}:\$\{props\.rowKey\}`\}/)
  assert.match(cards, /loaded\.source_session_id !== sessionId && loaded\.target_session_id !== sessionId/)
  assert.match(cards, /exchangeParticipant\(exchange, sessionId\)/)
  assert.match(cards, /exchangeSnapshot\?\.eventSeq === event\.seq/)
  assert.match(cards, /const lastDetailRequestSeq = useRef<number \| null>\(null\)/)
  assert.match(cards, /lastDetailRequestSeq\.current = event\.seq/)
  assert.match(cards, /lastDetailRequestSeq\.current === event\.seq/)
  assert.match(cards, /\[event\.seq, exchangeId, loading, cancelling, open, snapshotCurrent, workspaceRevision\]/)
  assert.match(cards, /setLoadError\(''\)/)
  assert.match(cards, /Remove queued message/)
  assert.match(cards, /End conversation/)
})

test('all cross-chat records share the current Mac directional bubble surface', () => {
  const imported = fs.readFileSync(path.resolve('src/components/ImportedCrossChatDeliveryCard.tsx'), 'utf8')
  assert.match(cards, /export function CrossChatMessageSurface/)
  assert.match(cards, /backgroundColor: light \? '#eee5fb' : '#332444'/)
  assert.match(cards, /borderColor: light \? '#bca5dc' : '#685080'/)
  assert.match(cards, /alignSelf: incoming \? 'flex-end' : 'flex-start'/)
  assert.match(cards, /Math\.min\(760, Math\.max\(0, layoutWidth - 28\) \* \(layoutWidth <= 480 \? 0\.94 : 0\.82\)\)/)
  assert.match(cards, /paddingHorizontal: layoutWidth <= 480 \? 10 : 13/)
  assert.match(cards, /flexShrink: 1, minWidth: 0/)
  assert.match(cards, /marginLeft: 'auto'/)
  assert.doesNotMatch(cards, /LinearGradient|conversationAccent|conversationShadow/)
  assert.match(imported, /<CrossChatMessageSurface identity=\{identity\} incoming/)
  assert.match(imported, /Source request/)
  assert.match(rows, /<ImportedCrossChatDeliveryCard[^\n]*layoutWidth=\{layoutWidth\}/)
  assert.match(rows, /<CrossChatHandoffCard[^\n]*fontScale=\{fontScale\} layoutWidth=\{layoutWidth\}/)
})

test('each exchange leg has readable Markdown, status, and exact available actions', () => {
  assert.match(cards, /const displayedLegs = legId \? conversationLegs\.filter\(leg => leg\.id === legId\) : conversationLegs/)
  assert.match(cards, /displayedLegs\.map\(\(leg, index\) =>/)
  assert.match(rows, /legId=\{row\.crossChatLegId\} anchorTs=\{row\.anchorTs\}/)
  assert.match(cards, /const actionMessage = actionLeg\?\.id === leg\.id/)
  assert.match(cards, /const incoming = leg\.target_session_id === sessionId && !fromThisChat/)
  assert.match(cards, /title=\{incoming \? sourceTitle : \x60To \$\{targetTitle\}\x60\}/)
  assert.match(cards, /interface CrossChatConversationLeg extends CrossChatExchangeLeg/)
  assert.match(cards, /bodyTruncated: latestExchangeBoolean\(ordered, candidate => candidate\.handoff_body_truncated\) === true/)
  assert.match(cards, /if \(leg\.bodyTruncated\) return true/)
  assert.match(cards, /if \(!body\) return true/)
  assert.match(cards, /bodyTruncated: false/)
  assert.match(cards, /<MarkdownContent value=\{\x60\$\{visibleBody\}/)
  assert.match(cards, /onRequestFull=\{\(\) => \{ setOpen\(true\); void loadExchange\(\) \}\}/)
  assert.match(cards, /Could not load full message/)
  assert.match(cards, /Stops future messages; work already in progress may still finish\./)
  assert.match(cards, /conversationBodyToggle: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /conversationDetailsToggle: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /conversationAction: \{ minWidth: 44, minHeight: 44/)
  assert.match(cards, /accessibilityLiveRegion="polite"[\s\S]*Queued message removed\./)
})

test('mobile message expansion stays bounded and authenticated headings report navigation failure', () => {
  assert.match(cards, /const CROSS_CHAT_BODY_CHUNK = 4_000/)
  assert.match(cards, /const CROSS_CHAT_LONG_MESSAGE_CHARS = 640/)
  assert.match(cards, /const CROSS_CHAT_LONG_MESSAGE_LINES = 10/)
  assert.match(cards, /completeVisibleBody\.slice\(0, limit\)/)
  assert.match(cards, /fullText\.slice\(0, bodyLimit\)/)
  assert.match(cards, /const moreBodyAvailable = Boolean\(envelopeId\) && \(!fullText \|\| \(truncated && !body\)\)/)
  assert.match(cards, /if \(moreBodyAvailable\) \{ void loadBody\(\); return \}/)
  assert.match(cards, /setExpanded\(value => !value\)/)
  assert.match(cards, /The referenced chat is not available in this server workspace/)
  assert.match(cards, /This chat is not available in the current server workspace/)
  assert.match(cards, /timelineWorkspaceProfileCurrent\(scope\)\) setError/)
  assert.match(cards, /sessions\.find\(candidate => candidate\.id === id\)\?\.title/)
  assert.match(cards, /useAppStore\(state => state\.sessions\)/)
  assert.match(cards, /const errorText = exchange\?\.error \|\| conversationLegs\.find/)
  assert.match(memory, /handoff_preview: truncateText\(event\.handoff_preview, MESSAGE_FIELD_LIMIT\)/)
  assert.match(memory, /source_title: truncateText\(event\.source_title, TIMELINE_LABEL_LIMIT\)/)
  assert.match(memory, /event\.digest, event\.handoff_preview,[\s\S]*event\.output/)
})

test('timeline route history preserves exact local markers and makes remote or hidden routes inert', () => {
  assert.match(inlineReferences, /const legacy = reference\.action === 'route' \? `@@\$\{reference\.display_title_snapshot\}` : null/)
  assert.match(inlineReferences, /const displayText = text\.slice\(reference\.source_text_start, reference\.source_text_end\)/)
  assert.match(inlineReferences, /reference\.target_kind === 'secure_peer' && reference\.action === 'instruction'/)
  assert.match(rows, /timelineInlineReferencesForText\(visible, inlineRoutes\.references, sessionId\)/)
  assert.match(rows, /\.\.\.inlineRoutes\.fallbackReferences/)
  assert.match(rows, /readOnlyReferenceKeys=\{readOnlyReferenceKeys\}/)
  assert.match(rows, /if \(timelineChatReferenceIsRemote\(reference\)\) return/)
  assert.match(markdown, /const interactive = !insideLink[\s\S]*inlineRouteReferenceIsInteractive\(segment\.reference\)/)
  assert.match(markdown, /accessibilityRole=\{interactive \? 'link' : undefined\}/)
  assert.match(markdown, /onPress=\{interactive \? \(\) => onChatReferencePress\?\.\(segment\.reference!\) : undefined\}/)
  assert.match(cards, /const readOnly = remote \|\| readOnlyReferenceKeys\.has\(key\)/)
  assert.match(cards, /if \(readOnly\) return <View[\s\S]*accessibilityRole="text"/)
  assert.match(markdown, /UITextView as SelectableText/)
  assert.match(markdown, /splitInlineRouteMarkerText\(node\.content, prepared\.markers\)/)
})

test('instruction exchanges retain their meaning in the unified conversation details', () => {
  assert.match(types, /export type AgentCrossChatRouteAction = 'instruction' \| 'request_reply'/)
  assert.match(types, /initial_action\?: AgentCrossChatRouteAction \| null/)
  assert.match(types, /exchange_initial_action\?: AgentCrossChatRouteAction \| null/)
  assert.match(cards, /candidate => candidate\.exchange_initial_action/)
  assert.match(cards, /label="Started as" value=\{initialAction === 'instruction' \? 'Instruction' : 'Question with replies'\}/)
  assert.match(cards, /accessibilityLabel=\{`Conversation status: \$\{stateLabel\}`\}/)
  assert.match(cards, /accessibilityState=\{typeof expanded === 'boolean' \? \{ expanded \} : undefined\}/)
  assert.match(types, /exchange_authorization_kind\?: 'explicit_prompt' \| 'configured_route' \| null/)
})
