import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = path => readFileSync(resolve(root, path), 'utf8').replace(/\/\/# sourceMappingURL=.*$/gm, '')
const target = resolve(root, 'src/terminal/xtermAssets.ts')
mkdirSync(dirname(target), { recursive: true })
writeFileSync(target, [
  '// Generated by scripts/embed-xterm.mjs. Do not edit by hand.',
  `export const XTERM_JS = ${JSON.stringify(read('node_modules/@xterm/xterm/lib/xterm.js'))}`,
  `export const FIT_JS = ${JSON.stringify(read('node_modules/@xterm/addon-fit/lib/addon-fit.js'))}`,
  `export const XTERM_CSS = ${JSON.stringify(read('node_modules/@xterm/xterm/css/xterm.css'))}`,
  '',
].join('\n'))
